import * as express from 'express'
import * as mongoose from 'mongoose'
import * as session from 'express-session'
import * as connectMongo from 'connect-mongo'
import * as methodOverride from 'method-override'
import * as passport from 'passport'
import * as flash from 'connect-flash'
